# Decision Trees - Classification

In [3]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error

In [7]:

# columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety"]
Dataset = pd.read_csv("vi/ML Algorithms/Dataset/car_evaluation.csv", names=["buying", "maint", "doors", "persons", "lug_boot", "safety","decision"])
Dataset["persons"]= Dataset["persons"].replace("more",7)
Dataset["doors"] = Dataset["doors"].replace("5more",6)

def Output(decision):
    if decision == 'vgood':
        return 5
    elif decision == 'good':
        return 4
    elif decision == 'acc':
        return 3
    else:
        return 1

Dataset["Output"] = Dataset["decision"].apply(Output)


In [8]:
Dataset


buying  maint doors persons lug_boot safety decision  Output
0     vhigh  vhigh     2       2    small    low    unacc       1
1     vhigh  vhigh     2       2    small    med    unacc       1
2     vhigh  vhigh     2       2    small   high    unacc       1
3     vhigh  vhigh     2       2      med    low    unacc       1
4     vhigh  vhigh     2       2      med    med    unacc       1
...     ...    ...   ...     ...      ...    ...      ...     ...
1723    low    low     6       7      med    med     good       4
1724    low    low     6       7      med   high    vgood       5
1725    low    low     6       7      big    low    unacc       1
1726    low    low     6       7      big    med     good       4
1727    low    low     6       7      big   high    vgood       5

[1728 rows x 8 columns]

In [9]:
X = Dataset[["doors", "persons"]]
Y = Dataset["Output"]

In [11]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3, random_state = 50)

Model = DecisionTreeClassifier()
Model.fit(X_train, Y_train)
Predict = Model.predict(X_test)
test_Predict = Model.predict([[6,7]])
Accuracy = mean_squared_error(Y_test,Predict)
test_Predict,Accuracy

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(array([1]), 1.834296724470135)

In [12]:
Predict = Model.predict(X_test)

In [13]:
Predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [31]:
Model.predict([[6,7]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])